name: ci

on:
  - push

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: taehoio-global
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure gcloud docker
        run: |
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev
      - name: Setup
        run: |
          git config --global url."https://${{ secrets.GH_ACCESS_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - name: Build and push
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            asia-northeast1-docker.pkg.dev/taehoio-global/docker-registry/taehoio-strapi:${{ github.sha }}
